### ISSUE TITLE
BUG - Quality Items removing everything except it self from the items. Vanilla Enchantments seem to be excluded.

### ISSUE THREAD

**Issue by Zhaaaaaaaaa** [Steel-Dev/ItemQualities#18] opened 2022-07-07 21:06 UTC
**Describe the bug - Please describe CLEARLY what went wrong.**

**Installing this plugin. Successfully Installed.** version 1.1.0

> Any item taken out of Creative or Crafted Adds the random Quality like it is supposed to.

> It messes up any other Plugin. Whether it is Enchantments, Lore Name or Lore Description.

> Most Noticeable with Tridents and Elytras since they sort of 'reload' or something during / after use.

> Adding such modified items into something like Shopkeeper resets the item into a Item Quality (removes all lore, enchantments etc.) and creates a duplicate. (not an issue if you're in staff mode doing staff stuff. but thought I should mention this if it has useful info to it.)

**To Reproduce - Please describe the steps you took to have this issue occur, if any.**
As explained above, basicly.

**Expected behavior - Please describe the behavior you expected.**
As explained above, basicly.

**Screenshots - Provide any applicable screenshots.**
Unnecessary.

**Server Information - Please provide your server version, server build version (e.g paper 1.18.2 build #100)**
Paper 1.18.1 AND Paper 1.18.2 that I upgraded to.
'This server is running **Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT (Git:df630a2 on ver/1.18.2)**
_Previous version: git-Paper-216 (MC:1.18.1)_

**Additional context - Please describe any additional information CLEARLY here.**
Plugins I'm using that seem to be interfering
CrazyEnchantments
CrazyEnchantments - Its GUI (Althought I suspect it is the Author of Crazy Enchantment's fault as Jobs GUI is not bothered by your plugin)
LoreAttributesRecorded

Plugins I suspect may have difficulties with your Plugin but **I have not tested it out properly, if you would, by any chance like me to do so... here is my discord:** ★ Zhaaaaaaaaa ★#1533

**I'm pretty sure you can pretty much ignore this list until reports are made**

Shopkeepers <- the glitch as mentioned above in "Describe Bug" section
Angelchest <- might do the reset bug
ExecutableItems (Free version) <- Have not tested as I'm overloaded with other things, but I can. or I'll just report it seperately.
Jobs <- Items bought from its Shop <- same thing, not tested yet.
RoseStacker <- Items bought from its Shop <- same thing, not tested yet.
PlayerAuctions <- Items bought from its Shop <- same thing, not tested yet.

**Additionally, I would just like to thank you for your plugin. Nice work and I'll be adding some suggestions sometime later.**
Also sorry if my report was very cluttered or badly written.

**Comment by Steel-Dev** [comment] 2022-07-07 23:57
There really is no way of properly fixing this.

Since any custom enchantment plugins uses _lore_ to display their enchantments (vanilla enchantments don't, fun fact) since it's impossible for them to display enchantments like the vanilla ones do (because it's the client displaying it, but the client doesn't know of said custom enchantments existence, and hence doesn't know how to display them like it does vanilla enchantments)

If I were to ADD to the lore instead of setting, it'd cause another major issue, which is constantly repeating the same lore over and over to the point where so much duplicated information would display and the lore tooltip would go off-screen.

So, there's really no way I can properly fix the lore issue.

As for the others, I don't really know, either. Nothing I can do about problems caused by other plugins, honestly.

**Comment by Steel-Dev** [comment] 2022-07-08 00:05
Oh, also, this appears to be a duplicate of #16, more or less. While yours isn't specifically about custom enchantments, both are the same issue. I will be closing this one. If you have more to say, please comment on #16 or make another issue (if it's not another duplicate)

**Closed by Steel-Dev** 2022-07-08 00:05 UTC
Labels: bug
